### ISSUE TITLE
the error @babel/plugin-proposal-private-property-in-object in babel-preset-two-app

### ISSUE THREAD

**Issue by qiuysh** [qiuysh/create-two-scripts#28]
```
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)

```

**Comment by qiuysh** [comment]
https://github.com/qiuysh/create-two-scripts/pull/29
